### ISSUE TITLE
AttributeError: module 'hyperjet' has no attribute 'Jet'

### ISSUE THREAD

**Issue by andreacortis** [oberbichler/HyperJet#28]
Hello,

I am trying to follow your `quickstart.md` but I find this error. could you please help me?

I have installed with 

```
>> pip install git+https://github.com/oberbichler/HyperJet
```

then

```
In [2]: import hyperjet as hj

In [3]: x, y = hj.Jet.variables([3, 6])
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-1bbea4a89a88> in <module>
----> 1 x, y = hj.Jet.variables([3, 6])

AttributeError: module 'hyperjet' has no attribute 'Jet'

```

Thanks

**Comment by oberbichler** [comment]
Hi,
I made some major changes and have not updated the documentation yet. Sorry for that.

You can find an [updated quickstart in the README](https://github.com/oberbichler/HyperJet#quickstart). You can also [take a look at the tests](https://github.com/oberbichler/HyperJet/blob/main/tests/test_DDScalar.py).

Greetings

**Comment by andreacortis** [comment]
Thank you Thomas. If I may ask, would you be willing to have an offline conversation to help me out with the applications of the HyperDual numbers? I was so far able to implement a simple NewtonRaphson algo, but I am having difficulties understanding how to apply them to, say, solving an ODE or a FD scheme. Maybe you could add a reference to the readme, or a few simple examples to get people started. Thanks!

**Comment by oberbichler** [comment]
Sure. I wrote an email to the address in your profile.
