### ISSUE TITLE
Sqrt of 0.0

### ISSUE THREAD

**Issue by leolapidus** [oberbichler/HyperJet#3]
https://github.com/oberbichler/HyperJet/blob/0ab72b64bbb35a8c180404e43d3819fe41136c7b/include/hyperjet/Jet.h#L297

Have you tried what happens if one takes the square root of 0.0?

```python
>>> import hyperjet as hj
>>> a = hj.Jet(0.0, [1])
>>> np.sqrt(a)
__main__:1: RuntimeWarning: divide by zero encountered in sqrt
Jet<0.000000>
```

I'm not sure if this Warning is caused by the division by 0.0 inside the Jet implementation or somewhere in numpy.

Armin

**Comment by oberbichler** [comment]
The problem is that the derivative of `Sqrt(x)` is `1/(2 * Sqrt(x))`. The derivative is not defined for `x=0` even with AD.
